MODEL:
  arch: gcn  # backbone network architecture



TRAIN:
  exp_name: gcn_train
  num_points: 1024
  pt_norm: False  # input normalization
  batch_size: 32
  test_batch_size: 16
  epochs: 100
  lr: 1e-3
  momentum: 0.9
  eval: False
  dropout: 0.5
  no_cuda: False
