MODEL:
  arch: vit  # backbone network architecture
  point_size: 1024
  cluster_num: 4
  num_classes: 40
  dim: 1024
  depth: 4
  heads: 16
  mlp_dim: 2048
  emb_dropout: 0.1


TRAIN:
  exp_name: vit_new
  num_points: 1024
  pt_norm: False  # input normalization
  batch_size: 32
  test_batch_size: 16
  epochs: 350
  lr: 0.1
  momentum: 0.9
  eval: False
  dropout: 0.5
  no_cuda: False
